# Generated by Django 5.0.6 on 2024-07-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='office_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
